title: Lisa Funke - Animation Student in Paris @ Gobelins
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Animation Student in Paris @ Gobelins
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.lisafunke.art" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections:
  observations:
    output: false
  director:
    output: false
